# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=150)),
                ('movie_director', models.CharField(max_length=100)),
                ('ratings', models.FloatField()),
                ('certificate', models.CharField(max_length=5)),
                ('duration', models.FloatField()),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField()),
                ('movie_image_url', models.URLField()),
                ('movie_video_url', models.URLField()),
                ('movie_credit_summary', models.CharField(max_length=300)),
            ],
        ),
    ]
