# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170603_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_credit_summary',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_video_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
