# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170603_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_links',
            fields=[
                ('movie', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('movie_links', models.URLField()),
            ],
        ),
    ]
