# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_links',
            new_name='Movie_link',
        ),
    ]
